version: '2'
services:
  nginx:
    image: nginx:latest
    container_name: docker-web-nginx
    ports:
     - "80:80"
    volumes:
     - ./nginx/site:/usr/share/nginx/html
     - ./nginx/conf:/etc/nginx:ro
     - ./nginx/log:/var/log/nginx
    depends_on:
     - phpfpm
    networks:
      lemp-network:
        ipv4_address: ${LEMP_NGINX_IP}

  phpfpm:
    image: bitnami/php-fpm:latest
    container_name: docker-web-phpfpm
    #ports:
    # - "9000:9000" 
    volumes:
    # - ./php-fpm/php-fpm.conf:/opt/bitnami/php/etc/php-fpm/php-fpm.conf
     - ./nginx/site:/usr/share/nginx/html
    networks:
      lemp-network:
        ipv4_address: ${LEMP_PHP7FPM}

  postgresql:
    image: postgres:9.3
    container_name: docker-web-postgresql
    restart: always
    environment:
      POSTGRES_PASSWORD: asdf
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
      - ./postgresql/conf:/etc/postgresql/
    ports:
      - "5432:5432"
    networks:
      lemp-network:
        ipv4_address: ${LEMP_POSTGRES_IP}

networks:
  lemp-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${LEMP_SUBNET}
          gateway: ${LEMP_GATEWAY}
